import { Inter } from "next/font/google";
import "../assets/scss/custom/custom.css";
import "../assets/scss/style/style.css";
import "../assets/scss/default/default.css";
import "./globals.css";
import "../assets/js/jquery.js";
import { Providers } from "./redux/provider";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SimpleHeader from "../components/SimpleHeader";
import './globals.css';
import ToastProvider from "../components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Compare Web",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Providers>
            <html lang="en">
                <body className="bg-[#E6E7EE]">
                    {children}
                    <ToastProvider />
                </body>
            </html>
        </Providers>
    );
}
