export const categories = [
    {
        icon: "📱",
        name: "Mobile Devices",
        bIcon: "electronics-icon.png",
        subCategories: [
            { name: "Smartphones", uniqueName: "smartphones", path: "/phone" },
            { name: "Tablets", uniqueName: "tablets" },
            { name: "E-Readers", uniqueName: "e-readers" },
        ],
    },
    {
        icon: "🔧",
        name: "Computer Components",
        bIcon: "computer-parts-icon.png",
        subCategories: [
            { name: "Graphics Cards", uniqueName: "graphics-cards" },
            { name: "CPUs", uniqueName: "cpus" },
            { name: "Enterprise CPUs", uniqueName: "enterprise-cpus" },
            { name: "Mobile Chipsets", uniqueName: "mobile-chipsets" },
            { name: "Motherboards", uniqueName: "motherboards" },
            { name: "SSDs", uniqueName: "ssds" },
            { name: "Memory", uniqueName: "memory" },
            { name: "PC Cases", uniqueName: "pc-cases" },
        ],
    },
    {
        icon: "🎮",
        name: "Entertainment",
        bIcon: "entertainment-icon.png",
        subCategories: [
            { name: "Video Streaming Services", uniqueName: "video-streaming" },
            { name: "Streaming Devices", uniqueName: "streaming-devices" },
            { name: "Game Consoles", uniqueName: "gaming-consoles" },
            { name: "VR Headsets", uniqueName: "vr-headsets" },
            { name: "Projectors", uniqueName: "projectors" },
            { name: "TVs", uniqueName: "tvs" },
            { name: "Drones", uniqueName: "drones" },
        ],
    },
    {
        icon: "🚗",
        name: "Transportation",
        bIcon: "transport-icon.png",
        subCategories: [
            { name: "Electric Scooters", uniqueName: "electric-scooters" },
            { name: "Electric Bikes", uniqueName: "electric-bikes" },
            { name: "GPS Navigation Systems", uniqueName: "gps-navigation" },
            { name: "Cars", uniqueName: "cars" },
        ],
    },
    {
        icon: "⌚",
        name: "Wearables",
        bIcon: "wearables-icon.png",
        subCategories: [
            { name: "Smartwatches", uniqueName: "smartwatches" },
            { name: "Fitness Trackers", uniqueName: "fitness-trackers" },
            { name: "Sports Watches", uniqueName: "sports-watches" },
        ],
    },
    {
        icon: "📷",
        name: "Photo & Video",
        bIcon: "camera-icon.png",
        subCategories: [
            { name: "Cameras", uniqueName: "cameras" },
            { name: "Camera Lenses", uniqueName: "camera-lenses" },
            { name: "Camcorders", uniqueName: "camcorders" },
            { name: "Action Cameras", uniqueName: "action-cameras" },
        ],
    },

    {
        icon: "💻",
        name: "Computer Components",
        bIcon: "computer-parts-icon.png",
        subCategories: [
            { name: "Processors", uniqueName: "processors" },
            { name: "Graphics Cards", uniqueName: "graphics-cards" },
            { name: "Memory", uniqueName: "memory" },
        ],
    },
    {
        icon: "💻",
        name: "Computers & Accessories",
        bIcon: "computers-icon.png",
        subCategories: [
            { name: "Laptops", uniqueName: "laptops" },
            { name: "Gaming PCs", uniqueName: "gaming-pcs" },
            { name: "All-In-One Computers", uniqueName: "all-in-one-computers" },
            { name: "Mini PCs", uniqueName: "mini-pcs" },
            { name: "Monitors", uniqueName: "monitors" },
            { name: "Routers", uniqueName: "routers" },
            { name: "Wi-Fi Extenders", uniqueName: "wifi-extenders" },
            { name: "Keyboards", uniqueName: "keyboards" },
            { name: "Mice", uniqueName: "mice" },
        ],
    },

    {
        icon: "🎮",
        name: "Entertainment",
        bIcon: "entertainment-icon.png",
        subCategories: [
            { name: "Gaming Consoles", uniqueName: "gaming-consoles" },
            { name: "Games", uniqueName: "games" },
            { name: "Streaming Devices", uniqueName: "streaming-devices" },
        ],
    },
    {
        icon: "📱",
        name: "Apps & Software",
        bIcon: "software-icon.png",
        subCategories: [
            { name: "Messaging Apps", uniqueName: "messaging-apps" },
            { name: "Dating Apps", uniqueName: "dating-apps" },
            { name: "Health & Fitness Apps", uniqueName: "health-fitness-apps" },
            { name: "Productivity Apps", uniqueName: "productivity-apps" },
            { name: "Weather Apps", uniqueName: "weather-apps" },
            { name: "OS", uniqueName: "operating-systems" },
        ],
    },
    {
        icon: "📚",
        name: "Education",
        bIcon: "education-icon.png",
        subCategories: [
            { name: "Online Courses", uniqueName: "online-courses" },
            { name: "Educational Software", uniqueName: "educational-software" },
            { name: "Learning Tools", uniqueName: "learning-tools" },
            { name: "Study Materials", uniqueName: "study-materials" },
        ],
    },

    {
        icon: "🏡",
        name: "Home & Garden",
        bIcon: "home-garden-icon.png",
        subCategories: [
            { name: "Air Fryers", uniqueName: "air-fryers" },
            { name: "Pressure Cookers", uniqueName: "pressure-cookers" },
            { name: "Vacuum Cleaners", uniqueName: "vacuum-cleaners" },
            { name: "Robot Vacuum Cleaners", uniqueName: "robot-vacuum-cleaners" },
            { name: "Washing Machines", uniqueName: "washing-machines" },
            { name: "Combo Washer Dryers", uniqueName: "combo-washer-dryers" },
            { name: "Tumble Dryers", uniqueName: "tumble-dryers" },
            { name: "Coffee Machines", uniqueName: "coffee-machines" },
            { name: "Commercial Coffee Machines", uniqueName: "commercial-coffee-machines" },
            { name: "Refrigerators", uniqueName: "refrigerators" },
            { name: "Dishwashers", uniqueName: "dishwashers" },
            { name: "Robotic Lawn Mowers", uniqueName: "robotic-lawn-mowers" },
            { name: "Lawn Mowers", uniqueName: "lawn-mowers" },
        ],
    },

];

export const mobileBrands = [
    "360 N7",
    "Acer",
    "AGM",
    "Alcatel",
    "Allview",
    "Amazon",
    "Apple",
    "Archos",
    "Asus",
    "Balmuda",
    "BenQ",
    "Black Shark",
    "BlackBerry",
    "Blackphone",
    "Blackview",
    "BLU",
    "Bluboo",
    "Boost Mobile",
    "BQ Aquaris",
    "Brand",
    "Bush",
    "Carbon",
    "Cat",
    "Cherry Mobile",
    "CMF",
    "Coolpad",
    "Creo",
    "Crosscall",
    "Cubot",
    "Digione",
    "Doogee",
    "Doro",
    "EE",
    "Elephone",
    "Energizer",
    "Escobar",
    "Essential",
    "Fairphone",
    "Figi",
    "Fossibot",
    "Freedom",
    "Freetel",
    "FreeYond",
    "Fujitsu",
    "Geeksphone",
    "General Mobile",
    "Gigabyte",
    "Gigaset",
    "Gionee",
    "Google",
    "Haier",
    "Hammer",
    "Hisense",
    "HMD",
    "HomTom",
    "Honor",
    "Hotwav",
    "HP",
    "HTC",
    "Huawei",
    "Hyundai",
    "ID2ME",
    "Infinix",
    "Innos",
    "INOI",
    "iQOO",
    "iRULU",
    "Itel",
    "JiaYu",
    "Jio",
    "Jolla",
    "Karbonn",
    "Kazam",
    "Kodak",
    "Kogan",
    "Kyocera",
    "Land Rover",
    "Lava",
    "Leagoo",
    "LeEco",
    "Leica",
    "Lenovo",
    "Letv",
    "LG",
    "Linshof",
    "Mara Phones",
    "Marshall",
    "Maxwest",
    "Maze",
    "Meitu",
    "Meizu",
    "Micromax",
    "Microsoft",
    "Mobistel",
    "Motorola",
    "Movi",
    "MyPhone",
    "Nextbit",
    "Nokia",
    "Nomu",
    "Nothing",
    "NuAns",
    "O+",
    "Obi Worldphone",
    "OnePlus",
    "Onyx",
    "Oppo",
    "Orange",
    "Oukitel",
    "Palm",
    "Panasonic",
    "Pantech",
    "Pentagram",
    "Philips",
    "Pine64",
    "Planet Computers",
    "Poco",
    "Polaroid",
    "Prestigio",
    "Punkt.",
    "Purism",
    "QMobile",
    "Razer",
    "Realme",
    "RED",
    "Redmi",
    "RIM",
    "RMQ5018",
    "Royole",
    "Samsung",
    "Saygus",
    "Sharp",
    "Shiftphones",
    "Sirin Labs",
    "Smartisan",
    "Solana Mobile",
    "Sonim",
    "Sony",
    "Spice",
    "Star",
    "Starmobile",
    "T-Mobile",
    "Tambo",
    "TCL",
    "Tecno",
    "ThL",
    "Thuraya",
    "Tonino Lamborghini",
    "TP-Link",
    "Turing",
    "Ulefone",
    "UMi",
    "Umidigi",
    "Unihertz",
    "Vaio",
    "Vernee",
    "Vertu",
    "Verykool",
    "Vestel",
    "Vivo",
    "Vodafone",
    "Wiko",
    "Wileyfox",
    "Xiaomi",
    "Xolo",
    "Yandex",
    "Yezz",
    "YotaPhone",
    "YU",
    "Zopo",
    "ZTE",
    "ZUK",
].sort();

export const sortByOptions = [
    { name: "Release date", id: 1 },
    { name: "Battery Life", id: 2 },
    { name: "Versus Score", id: 3 },
    { name: "Popularity", id: 4 },
    { name: "Price (low to high)", id: 5 },
    { name: "Price (high to low", id: 6 },
    { name: "User rating", id: 7 },
    { name: "Screen size", id: 8 },
];

export const designSpecs = [
    {
        id: "weight",
        label: "Weight",
        unit: "g",
        min: 8.2,
        max: 696,
    },
    {
        id: "thickness",
        label: "Thickness",
        unit: "mm",
        min: 5.4,
        max: 19.9,
    },
    {
        id: "width",
        label: "Width",
        unit: "mm",
        min: 54.8,
        max: 92.9,
    },
    {
        id: "height",
        label: "Height",
        unit: "mm",
        min: 109.7,
        max: 183.5,
    },
    {
        id: "waterResistance",
        label: "Water resistance",
        type: "checkbox",
        options: ["Waterproof", "Water resistant", "None"],
    },
    { id: "ipRating", label: "Ingress Protection (IP) rating" },
    { id: "waterproofDepth", label: "Waterproof depth rating" },
    { id: "minTemp", label: "Lowest potential operating temperature" },
    { id: "maxTemp", label: "Maximum operating temperature" },
    { id: "foldable", label: "Foldable" },
    { id: "qwerty", label: "Physical QWERTY keyboard" },
    { id: "repairIndex", label: "French Repairability Index" },
];

export const filters = [
    "Top 10",
    "Samsung",
    "Battery Life",
    "5G",
    "Headphone Jack",
    "Biggest Screen",
    "120Hz",
    "MicroSD Slot",
    "RAM",
    "Budget",
    "Biggest Battery",
    "Small",
    "Foldable",
];

export const phones = [
    {
        id: 1,
        name: "Realme GT 7 Pro Racing",
        image: "/realme-gt7.png",
        points: 75,
        screenSize: "6.78”",
        ram: "16GB",
        ppi: "450 ppi",
        battery: "6500 mAh",
    },
    {
        id: 2,
        name: "Samsung Galaxy F06 5G",
        image: "/samsung-f06.png",
        points: 45,
        screenSize: "6.7”",
        ram: "6GB",
        ppi: "262 ppi",
        battery: "5000 mAh",
    },
    {
        id: 3,
        name: "HMD Aura 2",
        image: "/hmd-aura2.png",
        points: 42,
        screenSize: "6.5”",
        ram: "4GB",
        ppi: "—",
        battery: "—",
    },
    {
        id: 4,
        name: "Asus Zenfone 12 Ultra",
        image: "/asus-zenfone12.png",
        points: 84,
        screenSize: "6.78”",
        ram: "16GB",
        ppi: "—",
        battery: "—",
    },
    {
        id: 5,
        name: "OnePlus 12R",
        image: "/oneplus-12r.png",
        points: 78,
        screenSize: "6.74”",
        ram: "16GB",
        ppi: "450 ppi",
        battery: "5500 mAh",
    },
    {
        id: 6,
        name: "iPhone 15 Pro Max",
        image: "/iphone-15-pro-max.png",
        points: 90,
        screenSize: "6.7”",
        ram: "8GB",
        ppi: "460 ppi",
        battery: "4500 mAh",
    },
    {
        id: 7,
        name: "Google Pixel 8 Pro",
        image: "/pixel-8-pro.png",
        points: 88,
        screenSize: "6.7”",
        ram: "12GB",
        ppi: "489 ppi",
        battery: "5000 mAh",
    },
    {
        id: 8,
        name: "Samsung Galaxy S24 Ultra",
        image: "/samsung-s24-ultra.png",
        points: 95,
        screenSize: "6.8”",
        ram: "12GB",
        ppi: "500 ppi",
        battery: "5000 mAh",
    },
    {
        id: 9,
        name: "Xiaomi 14 Pro",
        image: "/xiaomi-14-pro.png",
        points: 85,
        screenSize: "6.73”",
        ram: "16GB",
        ppi: "522 ppi",
        battery: "4880 mAh",
    },
    {
        id: 10,
        name: "Sony Xperia 1 V",
        image: "/sony-xperia-1v.png",
        points: 82,
        screenSize: "6.5”",
        ram: "12GB",
        ppi: "643 ppi",
        battery: "5000 mAh",
    },
    {
        id: 11,
        name: "Vivo X100 Pro",
        image: "/vivo-x100-pro.png",
        points: 86,
        screenSize: "6.78”",
        ram: "16GB",
        ppi: "452 ppi",
        battery: "5400 mAh",
    },
    {
        id: 12,
        name: "Oppo Find X7 Ultra",
        image: "/oppo-find-x7.png",
        points: 89,
        screenSize: "6.82”",
        ram: "16GB",
        ppi: "510 ppi",
        battery: "5000 mAh",
    },
    {
        id: 13,
        name: "Motorola Edge 50 Ultra",
        image: "/motorola-edge-50.png",
        points: 80,
        screenSize: "6.7”",
        ram: "12GB",
        ppi: "395 ppi",
        battery: "5000 mAh",
    },
    {
        id: 14,
        name: "Nothing Phone (2)",
        image: "/nothing-phone-2.png",
        points: 76,
        screenSize: "6.7”",
        ram: "12GB",
        ppi: "394 ppi",
        battery: "4700 mAh",
    },
    {
        id: 15,
        name: "Redmi K70 Pro",
        image: "/redmi-k70-pro.png",
        points: 81,
        screenSize: "6.7”",
        ram: "16GB",
        ppi: "444 ppi",
        battery: "5000 mAh",
    },
    // Add more devices until you reach 50
];
